import { CardProps } from 'ui/widgets/DayCard/DayCard'

export const may2025Cards: CardProps[] = [
	{
		variant: 'default',
		date: '05-01-2025',
		event: 'Праздник Весны и Труда',
		note: 'Праздничный день. Время для отдыха и семейных мероприятий.',
		breakfast: 'Блины с вареньем',
		lunch: 'Салат оливье',
		dinner: 'Шашлык',
		shoppingList: ['Мясо', 'Овощи', 'Хлеб'],
		calories: 2500,
		cookingTime: '2 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-02-2025',
		event: 'Выходной день',
		meal: 'Суп харчо',
		note: 'Поездка на дачу',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-03-2025',
		event: 'Выходной день',
		meal: 'Плов',
		note: 'Посадка рассады',
		cookingTime: '1.5 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-04-2025',
		event: 'Выходной день',
		meal: 'Пельмени',
		note: 'Отдых на природе',
		cookingTime: '45 мин',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-05-2025',
		event: '',
		meal: 'Гречка с курицей',
		note: 'Совещание в 10:00',
		cookingTime: '30 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-06-2025',
		event: '',
		meal: 'Салат Цезарь',
		note: 'Подготовка отчета',
		cookingTime: '20 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-07-2025',
		event: '',
		meal: 'Борщ',
		note: 'Встреча с клиентом',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'default',
		date: '05-08-2025',
		event: 'Выходной день',
		note: 'Подготовка к празднованию Дня Победы',
		breakfast: 'Овсянка с фруктами',
		lunch: 'Котлеты с пюре',
		dinner: 'Селедка под шубой',
		shoppingList: ['Картофель', 'Свекла', 'Майонез'],
		calories: 2200,
		cookingTime: '1.5 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'default',
		date: '05-09-2025',
		event: 'День Победы',
		note: 'Праздничный день. Участие в мероприятиях.',
		breakfast: 'Блины с медом',
		lunch: 'Плов',
		dinner: 'Салат оливье',
		shoppingList: ['Рис', 'Мясо', 'Овощи'],
		calories: 2600,
		cookingTime: '2 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-10-2025',
		event: 'Выходной день',
		meal: 'Шашлык',
		note: 'Поездка на природу',
		cookingTime: '2 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-11-2025',
		event: 'Выходной день',
		meal: 'Пельмени',
		note: 'Отдых дома',
		cookingTime: '45 мин',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-12-2025',
		event: '',
		meal: 'Суп лапша',
		note: 'Начало новой рабочей недели',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-13-2025',
		event: '',
		meal: 'Гречка с грибами',
		note: 'Подготовка презентации',
		cookingTime: '30 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-14-2025',
		event: '',
		meal: 'Салат с тунцом',
		note: 'Встреча с партнерами',
		cookingTime: '20 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-15-2025',
		event: '',
		meal: 'Борщ',
		note: 'Завершение проекта',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-16-2025',
		event: '',
		meal: 'Паста с соусом',
		note: 'Отчетность',
		cookingTime: '30 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-17-2025',
		event: 'Выходной день',
		meal: 'Плов',
		note: 'Поездка в гости',
		cookingTime: '1.5 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-18-2025',
		event: 'Выходной день',
		meal: 'Суп харчо',
		note: 'Отдых на даче',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-19-2025',
		event: '',
		meal: 'Гречка с курицей',
		note: 'Планирование недели',
		cookingTime: '30 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-20-2025',
		event: '',
		meal: 'Салат Цезарь',
		note: 'Совещание',
		cookingTime: '20 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-21-2025',
		event: '',
		meal: 'Борщ',
		note: 'Отчёт по кварталу',
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'default',
		date: '05-22-2025',
		event: '',
		note: 'Подготовка к конференции',
		breakfast: 'Тосты с авокадо',
		lunch: 'Суп-пюре из тыквы',
		dinner: 'Запечённая рыба с овощами',
		shoppingList: ['Авокадо', 'Рыба', 'Тыква', 'Сливки'],
		calories: 2100,
		cookingTime: '1 ч 20 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-23-2025',
		event: '',
		meal: 'Паста карбонара',
		note: 'Финализация проекта',
		cookingTime: '25 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-24-2025',
		event: 'Выходной день',
		meal: 'Шашлык',
		note: 'Выезд с друзьями',
		cookingTime: '2 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'default',
		date: '05-25-2025',
		event: 'Семейный день',
		note: 'Пикник в парке',
		breakfast: 'Смузи с ягодами',
		lunch: 'Сэндвичи',
		dinner: 'Пицца домашняя',
		shoppingList: ['Хлеб', 'Ветчина', 'Сыр', 'Томатный соус'],
		calories: 2300,
		cookingTime: '1 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	},
	{
		variant: 'cell',
		date: '05-26-2025',
		event: '',
		meal: 'Куриный суп',
		note: 'Планёрка в 11:00',
		cookingTime: '45 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-27-2025',
		event: '',
		meal: 'Гречка с котлетами',
		note: 'Подведение итогов недели',
		cookingTime: '35 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'default',
		date: '05-28-2025',
		event: 'Домашний день',
		note: 'Уборка и готовка',
		breakfast: 'Каша с изюмом',
		lunch: 'Рагу овощное',
		dinner: 'Суп лапша',
		shoppingList: ['Овощи', 'Мясо', 'Лапша', 'Молоко'],
		calories: 2000,
		cookingTime: '1 ч 10 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-29-2025',
		event: '',
		meal: 'Пельмени',
		note: 'Работа над новым проектом',
		cookingTime: '30 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'cell',
		date: '05-30-2025',
		event: '',
		meal: 'Омлет с сыром',
		note: 'Встреча с руководством',
		cookingTime: '20 мин',
		isAllBought: true,
		theme: 'dark'
	},
	{
		variant: 'default',
		date: '05-31-2025',
		event: 'Выходной день',
		note: 'Закрытие месяца, отдых',
		breakfast: 'Панкейки с сиропом',
		lunch: 'Чахохбили',
		dinner: 'Бургеры домашние',
		shoppingList: ['Фарш', 'Булочки', 'Соус', 'Листья салата'],
		calories: 2500,
		cookingTime: '1.5 ч',
		isAllBought: true,
		theme: 'dark',
		isDayOff: true
	}
]
